version: '3.8'
services:
  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama
    tty: true
    volumes:
      - ollama:/root/.ollama
    ports:
      - '${API_PORT:-8081}:11434'
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                device_ids: ['0']
                capabilities: [compute, utility]
  
  openwebui:
    container_name: open-webui
    restart: unless-stopped
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG:-main}
    build:
      context: .
      args:
        OLLAMA_BASE_URL: '/ollama'
      dockerfile: Dockerfile
    volumes:
      - open-webui:/app/backend/data
    ports:
      - ${WEBUI_PORT:-8080}:8080
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='

volumes:
  ollama: {}
  open-webui: {}
